import Head from 'next/head'
import styles from '../styles/Home/Home.module.css'
import Intro from "../component/Home/Intro"
import Shop from "../component/Shop/Shop"



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Intro />
      <Shop />
        

      </main>

  
    </div>
  )
}
